# Generated by Django 5.0.1 on 2025-11-26 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50, unique=True)),
                ("instrument_type", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trading_symbols",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="ScriptRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_name",
                    models.CharField(
                        choices=[
                            ("CAMARILLA", "Camarilla Levels"),
                            ("WHOLE_NUMBER", "Whole Number Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("run_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_success", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("log_details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "script_run_logs",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["-run_date", "script_name"],
                        name="script_run__run_dat_d92f49_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WholeNumberStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("trade_date", models.DateField(db_index=True)),
                ("high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("high_is_round", models.BooleanField(default=False)),
                ("low_is_round", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "whole_number_stocks",
                "ordering": ["-trade_date", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["-trade_date"], name="whole_numbe_trade_d_66f303_idx"
                    ),
                    models.Index(
                        fields=["symbol", "-trade_date"],
                        name="whole_numbe_symbol_f79b7d_idx",
                    ),
                ],
                "unique_together": {("symbol", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(db_index=True)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_data",
                        to="trading.tradingsymbol",
                    ),
                ),
            ],
            options={
                "db_table": "historical_data",
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-trade_date"],
                        name="historical__symbol__abe359_idx",
                    )
                ],
                "unique_together": {("symbol", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="CamarillaLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(db_index=True)),
                ("expiry_date", models.DateField()),
                (
                    "prev_open",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("prev_high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prev_low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prev_close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h4_level", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h4_sl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h4_target1", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h4_target2", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h4_target3", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h3_level", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h3_sl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h3_target1", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h3_target2", models.DecimalField(decimal_places=2, max_digits=12)),
                ("h3_target3", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l3_level", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l3_sl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l3_target1", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l3_target2", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l3_target3", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l4_level", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l4_sl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l4_target1", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l4_target2", models.DecimalField(decimal_places=2, max_digits=12)),
                ("l4_target3", models.DecimalField(decimal_places=2, max_digits=12)),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camarilla_levels",
                        to="trading.tradingsymbol",
                    ),
                ),
            ],
            options={
                "db_table": "camarilla_levels",
                "ordering": ["-trade_date", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["-trade_date", "symbol"],
                        name="camarilla_l_trade_d_6f08aa_idx",
                    )
                ],
                "unique_together": {("symbol", "trade_date")},
            },
        ),
    ]
