# Generated by Django 5.0.1 on 2025-11-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingsymbol",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="tradingsymbol",
            name="instrument_type",
            field=models.CharField(
                choices=[
                    ("STOCK", "Stock"),
                    ("FUTURE", "Future"),
                    ("OPTION", "Option"),
                    ("FUTIDX", "Future Index"),
                    ("FUTSTK", "Future Stock"),
                ],
                default="FUTIDX",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SymbolExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiries",
                        to="trading.tradingsymbol",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Symbol expiries",
                "unique_together": {("symbol", "expiry_date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="camarillalevel",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="camarillalevel",
            name="expiry_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camarilla_levels",
                to="trading.symbolexpiry",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="camarillalevel",
            unique_together={("symbol", "trade_date", "expiry_date")},
        ),
    ]
