# Generated by Django 5.0.1 on 2025-11-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_tradingsymbol_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="camarillalevel",
            name="camarilla_l_trade_d_6f08aa_idx",
        ),
    ]
